services:
  upsnap:
    cap_add:
      - NET_RAW # NET_RAW is required for privileged ping and network device scan (nmap)
    cap_drop:
      - ALL
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:5
    network_mode: host # host is required for WOL magic packets
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=${TZ:-America/Chicago}
      - UPSNAP_HTTP_LISTEN=0.0.0.0:${UPSNAP_PORT:-8090}
      - UPSNAP_SCAN_RANGE=${UPSNAP_SCAN_RANGE:-192.168.1.0/24}
    dns:
      - ${LOCAL_DNS_IP:-1.1.1.1}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wol.rule=${TRAEFIK_RULE:-Host(`wol.localhost`)}"
      - "traefik.http.routers.wol.entrypoints=${TRAEFIK_ENTRYPOINT:-web}"
      - "traefik.http.services.wol.loadbalancer.server.url=http://${LOCAL_IP:-127.0.0.1}:${UPSNAP_PORT:-8090}"

networks:
  traefik-net:
    external: true
