services:
  jellyfin:
    image: linuxserver/jellyfin:10.10.3
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Chicago}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL:-http://localhost:8096}
    volumes:
      - /opt/jellyfin/config:/config
      - /media/drobo/Videos/movies:/movies
      - /media/drobo/Videos/tv:/tv
      - /media/drobo/Videos/misc:/other/misc
      - /media/drobo/Downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=${TRAEFIK_RULE:-Host(`jellyfin.localhost`)}"
      - "traefik.http.routers.jellyfin.entrypoints=${TRAEFIK_ENTRYPOINT:-web}"
      - "traefik.http.services.jellyfin.loadbalancer.server.url=http://${LOCAL_IP:-127.0.0.1}:8096"

      - "traefik.http.middlewares.jellyfin-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.jellyfin-headers.headers.customrequestheaders.X-Forwarded-Port=443"
    
      # Middleware: disable buffering (important for streaming)
      - "traefik.http.middlewares.jellyfin-buffer.buffering.maxRequestBodyBytes=0"
      - "traefik.http.middlewares.jellyfin-buffer.buffering.memRequestBodyBytes=0"
    
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-headers,jellyfin-buffer"
    restart: unless-stopped

networks:
  traefik-net:
    external: true
