services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - paperless_internal
  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - paperless_internal
    env_file:
      - path: .env
        required: true
      - path: secrets.env
        required: false
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "${BIND_IP:-127.0.0.1}:8502:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file:
      - path: .env
        required: true
      - path: secrets.env
        required: false
    networks:
      - paperless_internal
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=${TRAEFIK_RULE:-Host(`paperless.localhost`)}"
      - "traefik.http.routers.paperless.entrypoints=${TRAEFIK_ENTRYPOINT:-web}"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.paperless-headers.headers.sslProxyHeaders.X-Forwarded-Proto=https"
      - "traefik.docker.network=traefik-net"

      - "traefik.http.middlewares.paperless-sec.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.paperless-sec.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.paperless-sec.headers.stsPreload=true"

      - "traefik.http.routers.paperless.middlewares=paperless-sec"
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless

      PAPERLESS_URL: ${PAPERLESS_URL:-https://paperless.localhost}
      PAPERLESS_ALLOWED_HOSTS: ${PAPERLESS_ALLOWED_HOSTS:-paperless.localhost}
      PAPERLESS_USE_X_FORWARD_HOST: true
      PAPERLESS_USE_X_FORWARD_PORT: true
      PAPERLESS_PROXY_SSL_HEADER: '["HTTP_X_FORWARDED_PROTO", "https"]'

volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  traefik-net:
    external: true
  paperless_internal:
