services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    volumes:
      - mealie-data:/app/data/
    networks:
      - traefik_proxy
    # ports:
    #   - 9091:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`mealie.prplalpca.com`)"
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.tls.certresolver=cloudflare"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik_proxy"
    environment:
      ALLOW_SIGNUP: "false"
      LOG_LEVEL: "DEBUG"

      DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'
      # =====================================
      # Postgres Config
      #POSTGRES_USER: mealie
      #POSTGRES_PASSWORD: mealie
      #POSTGRES_SERVER: postgres
      #POSTGRES_PORT: 5432
      #POSTGRES_DB: mealie
      # =====================================
      # Email Configuration
      # SMTP_HOST=
      # SMTP_PORT=587
      # SMTP_FROM_NAME=Mealie
      # SMTP_AUTH_STRATEGY=TLS # Options: 'TLS', 'SSL', 'NONE'
      # SMTP_FROM_EMAIL=
      # SMTP_USER=
      # SMTP_PASSWORD=

volumes:
  mealie-data:
    driver: local

networks:
  traefik_proxy:
    external: true

