services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    ports:
      - "${BIND_IP:-127.0.0.1}:8504:9000"
    volumes:
      - mealie-data:/app/data/
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=${TRAEFIK_RULE:-Host(`mealie.localhost`)}"
      - "traefik.http.routers.mealie.entrypoints=${TRAEFIK_ENTRYPOINT:-web}"
      - "traefik.http.routers.mealie.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-cloudflare}"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik-net"
    environment:
      ALLOW_SIGNUP: ${ALLOW_SIGNUP:-false}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'

volumes:
  mealie-data:
    driver: local

networks:
  traefik-net:
    external: true
